### ISSUE TITLE
あるドリブルで敵を抜くの体力回復

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#102]
![screenshot_2023-08-27_01-40-25](https://github.com/Cilda/UmaUmaChecker/assets/12384865/f0d93d42-fb00-42c4-9760-8f071f4da738)
![Clipboard01fdsafsd](https://github.com/Cilda/UmaUmaChecker/assets/12384865/e4373d1e-07da-434d-95ad-b376951b3a4a)
数十回やっても体力+９でした。

**Comment by Cilda** [comment]
GameWithを確認したところ、更新が行われていたので問題ないと思われます。
