### ISSUE TITLE
[Bug] 要検証・睡眠時間と作業能率にご認識された

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#103]
![Clipboard01ffsddsa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/5be35435-5f89-407c-8f64-d012711f277a)

![screenshot_2023-09-05_21-18-00](https://github.com/Cilda/UmaUmaChecker/assets/12384865/dcc504c8-5b69-4c6c-becd-beb58670287b)

**Comment by Cilda** [comment]
確認したところ、イベント自体がGameWithにないようなので手動で追加されるよう変更します。

**Comment by Cilda** [comment]
追加しました、次の更新でマルゼンスキーとゴールドシップの「彼の都の思い出は」が追加されます。
