### ISSUE TITLE
「パリの街にて」イベント誤認識

### ISSUE THREAD

**Issue by shishi** [Cilda/UmaUmaChecker#105]
**バグの説明**
イベント誤認識

**再現手順**

- 「育成ウマ娘」は育成中のウマ娘通りにセットされている。
- 該当イベント「パリの街にて」が発生する。

**想定される動作**

- 育成ウマ娘の「パリの街にて」が発生する。
  - 実際は他ウマ娘で発生する際の選択肢が表示される。
- GameWithにおいては「パリの街にて」は通常のイベントよりも選択肢が複雑そう。

![image](https://github.com/Cilda/UmaUmaChecker/assets/341746/ba81dd1f-583c-41cb-97e6-8ec4aef37997)

**スクリーンショット**

![screenshot_2023-09-28_21-18-43](https://github.com/Cilda/UmaUmaChecker/assets/341746/73a932ca-47e8-482c-814d-1636f9ecc66f)

**追加の内容**
問題に関するその他の内容があればここに記載します。

**Comment by Cilda** [comment]
#106 と同じ問題のため、同様の修正で対応します。

**Comment by Cilda** [comment]
#106 にて修正を行いました。
