### ISSUE TITLE
【要望】UIの多言語

### ISSUE THREAD

**Issue by Ran-gok** [Cilda/UmaUmaChecker#107]
こんにちは。
私は他の国のユーザーです。
機能要望についてissueカテゴリに問い合わせしろというので、 
こちらに来ました。

本題ですが、多言語対応は可能でしょうか？
今、日本、韓国、中国がうまむすめをオープンしたと聞いています。
UmaUmaCheckerは必要な機能だけを集めたとても良いプログラムだと思います。
なので、他の国でも利用できるように言語の機能もあればいいと思います。

個人的な考えはgamewithで他の国の言語に翻訳するのは無理だと思いますが、誤訳がたくさん出てくると思います。
UmaUmaCheckerのインターフェースUIだけ各国の言語に変えて、Tesseractに他の国の言語も認識できるようにプログラミングしてくれれば、
残りの翻訳部分はLibraryを個別に現地人がローカライズ翻訳して使ってもいいと思います。

厳しい要求でしょうか？
実際、ローカライズ言語をするためにbuildをしてみましたが、x64-windows-staticの部分でエラーが出てbuildできませんでした。私がビルドしながら考えたのが上の部分です。
インターフェースUIとTesseractをローカライズ言語で認識できるようにプログラミングされたら、
Libraryに手動翻訳くらいは十分できるだろうと判断しました。

とんでもない機能要求かもしれませんが、問い合わせをします。
あ...もしかしてcommissionが可能ですか？

**Comment by Cilda** [comment]
UIの言語対応は私で対応可能です。
Libraryに関しては、元データをGameWithから取得しているので私での翻訳は難しいです。
(データ形式を合わせれば、他の言語で名称やイベントが書かれていても動作に問題ありません。)
イベントの識別は.traineddataを別言語用へ変更すれば認識できると思います。

イベントデータの更新先は現在当リポジトリのURLで固定されているため、URLを設定ファイルで管理するようにします。

**Comment by Ran-gok** [comment]
@Cilda はい、私が言ったのはLibraryはGameWithの翻訳が難しく、誤訳が多いかもしれないので、それは現地の人が翻訳できるようにしておいて、UIだけ多言語サポートをしてくれればありがたいと言ったのです。

.traineddataについてですが、engも含めてコードに入力してもらえますか？ eng+jpnみたいな感じで可能でしょうか？

私が翻訳機で解釈をしているのですが、そうするとUIを変更できるようにしてくれるということですか？

多国籍言語を機能に含めるということでしょうか？

**Comment by Cilda** [comment]
Tesseractの言語指定をconfig.jsonに追加します。
UIの多言語化についてはこちらで対応します。
設定で言語の切り替えを行えるように考えています。

**Comment by Ran-gok** [comment]
@Cilda こんにちは!
天気が寒くなってきましたね。
多言語サポートをアップデートしてくれるなんて、とても嬉しいです。
私もUIアップデートが行われたらすぐに使えるように
Libraryファイルをローカライズ翻訳を少しずつしようと思っています。

そして、見ていて一つ思いついたのですが、機能の中にウィンドウを最上位に固定する機能は見当たらないようですが、この機能はどうですか？
あったらいいなと思いました。

とにかく多言語UI機能アップデートを快く承諾してくれてありがとうございました。
アップデートが待ち遠しいです :)

**Comment by Ran-gok** [comment]
@Cilda こんにちは。
お久しぶりです。
UmaUmaCheckerのLibraryに翻訳をして使ってみたいのですが、
プログラムを実行すると、自動更新(?)になるのか初期状態に戻るのですが、もしかしたら今v1.6.1で自動更新(?)をオフにする方法がありますか？
Libraryの翻訳した内容が出るか実験してみたいです。
もしかしたら、翻訳版で今実際に使用が可能なら、使用しながら
正式版がアップデートされるまで使ってみようかと思って。
今のv1.6.1では使えない部分でしょうか？

**Comment by Cilda** [comment]
起動時に更新するようになっていますが、機能をOFFにする仕組みは現在ないです。
GUIの翻訳はほとんど完成となりますので、他の機能と合わせて次のバージョンでリリースを行いたいと思います。
起動時に自動更新する機能も設定で切り替えられるようにします。

**Comment by Ran-gok** [comment]
@Cilda すごい！本当にすごいですね。
アップデートはもう終わりですか？
どうなるのか楽しみですね。
本当に本当にありがとうございます。

**Comment by Ran-gok** [comment]
こんにちは。お久しぶりです。
失礼ですが、もしかしてパッチの進捗はどれくらい残っていますか？

**Comment by Cilda** [comment]
後は設定ファイルにURLを追加するだけとなっていますので明日中には次バージョンで出すようにします。
遅れてすみません。

**Comment by Ran-gok** [comment]
@Cilda いいえ、謝る必要はありません。
更新してくださるだけでもありがたいです。
ただ、進捗がどうなっているのか気になって聞いてみただけです。
明日には更新されるんですね。
とても楽しみです。更新するのに大変だったでしょうね。
ありがとうございます。コーヒーでも買ってあげたいです :)

**Comment by Cilda** [comment]
更新しました。
Tesseractの言語は**TesseractLanguage**で、イベントデータの更新は**UpdateUrl**で、config.jsonを直接編集して変更できます。

**Comment by Ran-gok** [comment]
@Cilda ありがとうございます。とても嬉しいです。仕事中なので、まだ食べていません。 仕事が終わってからゆっくり味わう予定です。
改めてありがとうございました :)

**Comment by Ran-gok** [comment]
@Cilda こんにちは!
アップデートしていただいたUmaUmaCheckerをローカライズ実験しています。とりあえずは翻訳の状態でうまく出ています :)
しかし、気になる点と、聞きたいことがあります。

1.Languagesファイルの中にあるen,ja,koファイルは気にしなくていいし、tessdataファイルの中に.traineddataを入れればいいんですよね？
(今そうして使っています)

2.育成うまむすめの自動選択機能が認識率が低いです。
他の言語だからでしょうか？ もしかしたら認識率を上げる方法があるのでしょうか？
私はニックネームの記号を、タイキシャトル【 Bubblegum☆Memories 】のように入れています。と入れているのですが、もしかして問題ないでしょうか？[Bubblegum☆Memories ]に変えるべきですか？

3.うまむすめの手動選択の場合、コンボボックスの内容が1234...このように順番に並んでほしいのですが、もしかしてすぐに修正できる方法はありますか？
ダメなら、後でアップデートするときに覚えておいてくれるでしょうか？

4. ReplaceText.json このファイルはどんな機能をするのですか？
特殊文字といくつかないようですが... そのまま置いておいても問題ないのでしょうか？

質問はここまでです。また迷惑をかけたようで申し訳ありません。
そして、アップデートしてくださったこと本当に本当にありがとうございます (- -)(_ _) (クックック)

**Comment by Cilda** [comment]
> 1.Languagesファイルの中にあるen,ja,koファイルは気にしなくていいし、tessdataファイルの中に.traineddataを入れればいいんですよね？

tessdataフォルダ内にその言語用のtraineddataファイルを入れてください。

> 私はニックネームの記号を、タイキシャトル【 Bubblegum☆Memories 】のように入れています。と入れているのですが、もしかして問題ないでしょうか？[Bubblegum☆Memories ]に変えるべきですか？

**［］** を使って囲ってください。

> ReplaceText.json このファイルはどんな機能をするのですか？

そのまま変更なしで大丈夫と思います。

**Comment by Ran-gok** [comment]
@Cilda こんにちは。
回答通り修正しましたが、馬娘を選択するときに認識はうまくいかないですね。 日本語がないからそうなのでしょう。 手動で書かなければなりません。

最後に機能か質問があります。
設定ウィンドウの最後の部分にデバッグモード-イベントを認識できない場合、画面キャプチャ-これは報告機能ですか？
画面キャプチャができなかったスクリーンショットを開発者に送ってほしいということですか？
それとも画面キャプチャをしてプログラムがスクリーンショットでOCRをするということですか？
チェックしたら、何かたくさんAutoSaveファイルとして残ってたんですが...

ところで、私たちのコミュニティに既にアップデートバージョンが紹介されていますね。
私もローカライズして広報中です。
改めて翻訳ありがとうございました :)

**Comment by Cilda** [comment]
> 設定ウィンドウの最後の部分にデバッグモード-イベントを認識できない場合、画面キャプチャ-これは報告機能ですか？

報告に使用することもできます。
認識できないイベントを確認するために使うことがあります。

**Comment by Ran-gok** [comment]
@Cilda 回答ありがとうございます。

ところで、その機能が報告機能じゃなくて、 
認識できなかったイベントをスクリーンショットを撮った後に
OCR機能がスクリーンショットを分析して選択肢を表示するのですか？

自動的に認識すれば問題ないですが、認識が100%ではないので
それを補助する機能としてあるのか聞いてみたのです。

私の考えが正しいでしょうか？
認識ができない場合、自動的にスクリーンショットを撮ってそれをOCR認識をして
選択肢を見せる。

ローカライズ言語に変えてみたら...認識率が落ちるのは仕方ないですね。

**Comment by Ran-gok** [comment]
@Cilda あ...その機能が特別に働いて認識するわけではないんですね。
ローカライズ作業で認識率が落ちるので、認識率がもっと高くなる方法を考えるようになりました。

そして、最後に一つだけ質問があります。
どうしてもOCR認識ができない場合は、手動でイベントを探さなければならないのですが、
キャラクターだけ検索され、イベントは検索できないようになっていたのですが、
手動の機能は今は不可能ですよね？

上記の質問が最後になります。
今まで親切に答えてくれてありがとうございました。
UmaUmaCheckerの多言語アップデートもありがとうございました。
いつも、よく使っています:)

**Comment by Cilda** [comment]
現状では手動でイベントを検索する仕組みは実装されていません。
将来的にアプリ内部で使用されている設定をファイルで管理する予定なので、認識率を向上させることができる可能性はあります。
上記についてはしばらくお待ちいただくことになります。

**Comment by Ran-gok** [comment]
@Cilda なるほど、そんな計画があるんですね。
残りの更新は自分でやってくれるでしょうね :)
あ、、、あと質問はもうしないつもりだったんですけど、 
もしかしたら、Windows 11バージョンでプログラムがオンになるが、OCR認識ができないようだと報告が入るが、もしかしたら、解決方法や理由を知っていますか？
ユーザー権限、互換モードを試してもダメだと言ってましたよ...
最後の質問として残し、アップデートはゆっくり待っています。

**Comment by Cilda** [comment]
遅れてすみません。
現在、認識できないという問題が発生していないので解決策は分かりません。
具体的な症状などを教えていただければ調査をすることは可能です。

**Comment by Ran-gok** [comment]
@Cilda 
いいえ、大丈夫です。
実行できない理由については、
私もユーザーから聞いたので詳しくは分かりません。
その問題はWindows10では使用可能なので大丈夫だと思います。

そして今後バージョンアップをするでしょう、 
そこに機能的な部分に追加要請をしてみたいと思います。
後でバージョンアップが必要な時に入れてほしいです。

1.UmaUmaCheckerプログラムが最優先上位に表示する機能が
あったらいいなと思います。
インターネットウィンドウのように使用したり、フォルダを開く時、UmaUmaCheckerが他のウィンドウに隠れてしまうのを防止する機能のことです。

2.プログラムが100%認識できないことは知っています。
だから、手動で検索できる機能が必要ではないかと思います。
そして、Libraryの中にSkills.jsonがあるので、スキルも手動で検索できるようにするのはどうでしょうか？

3.今現在も認識率がかなり高いのですが、もっと認識率を上げるためには、
 今は大きなタイトルをスキャンしています、
大きなタイトルと最初の選択ボタンのほうにもスキャン機能を追加してさらに認識率を上げるのはどうかと思います。

4.これはオーバー機能かもしれませんが、イベントタイトルとその横に小さなアイコンが衣装を表示していました。
画像OCR機能を活用すれば、最初に開始時にキャラクターを選択しなくても、
画像OCRで勝負服のアイコンを検索し、キャラクターに合った選択肢を呼び出す機能です。
今の機能もとても良いのですが、このような機能があれば使うのに簡素化されると思います。

4番は複雑に見えますが、軽く言っただけです、
1,2,3はいつになるか分かりませんが、次のバージョンで追加してほしいです。
全部ではないにしてもね。

次のバージョンを作る時に参考にしていただければ幸いです。
多くのユーザーにUmaUmaCheckerを使ってほしいです。
天気が寒くなりますが、健康に気をつけて、次のバージョンでお会いしましょう。

改めて、今回の多言語バージョンアップ、ありがとうございました。

**Comment by Cilda** [comment]
1.に関しては前々から欲しいでしたので追加予定です。
2.は考えておきます。
3.既にタイトルの認識は行っているので、改善方法をもう少し考えてみます。
4.は少し複雑になるので時間がかかるかもしれません。
