### ISSUE TITLE
[Bug] Windows11でのマルチディスプレイ使用時反応がおかしい

### ISSUE THREAD

**Issue by Jonnyraiden** [Cilda/UmaUmaChecker#108]
**Windows11でのマルチディスプレイ使用時反応がおかしい**
Windows11に買い替えしたあとに発生
1. 3840×2160ディスプレイ使用時アプリ無反応(イベントが反映しない)
2. 1の状態で1920×1080ディスプレイ側にウマ娘アプリを動かすとアプリが正常に反映される
3. ４Kディスプレイの解像度を1920×1080に変更しマルチディスプレイの解像度を合わせた場合ウマ娘アプリを動かしてもイベントは反映しない

旧PC(Windows10)、同環境での使用時は正常に使用できた
スクリーンショットなどは正常に反応してる
なにが悪さしてるのか見当がつかない状況です

**Comment by Jonnyraiden** [comment]
上記バグの発生状況(3840×2160ディスプレイ側)動画URLです

https://youtu.be/KCSGT0qT3Xo

**Comment by Cilda** [comment]
動画を確認したところ、画面の輝度が通常より明るいように見えます。
こちらでも念のため検証を行いますが、Windows側でHDRなどの設定をしている場合、キャプチャ方式がBitBltですと正しく認識できないのでWindows10(1903以降)に変更して確認してみてください。

**Comment by Jonnyraiden** [comment]
ご回答ありがとうございます

原因がだいたい判明いたしました、悪さをしていたのは「システムの自動 HDR」設定だと思われます
スクショは撮れていましたが白飛びしていました
自動HDR ONの状態だと添付のようにスクショが白飛びしてアプリでイベントが認識できていなかったようです

![screenshot_2023-10-09_22-03-18](https://github.com/Cilda/UmaUmaChecker/assets/147433258/3ee63350-45d4-4cbd-8be8-4e60581b3fc3)

**Comment by Cilda** [comment]
問題が解決できてよかったです。

自動HDRを設定することはほとんどないと思うので、自動HDRで認識したいという要望があれば認識できるように対応したいと思います。
