### ISSUE TITLE
新衣装メジロブライトが認識されません。

### ISSUE THREAD

**Issue by rindenpapa** [Cilda/UmaUmaChecker#117]
［清らに星澄むスノーロリィタ］メジロブライト
なのに
［Illuminate you］メジロブライト
になっている為だと思われます。

お手数ですが修正お願いします。

**Comment by Cilda** [comment]
変更しました。
次のスクレイピングで修正されると思います。

**Comment by rindenpapa** [comment]
迅速な対応ありがとうございます。
