### ISSUE TITLE
ヴィブロスのサポートカードイベントの情報不備

### ISSUE THREAD

**Issue by ameteras2240** [Cilda/UmaUmaChecker#118]
ヴィブロスのサポートカードイベント「いつの間にかあまーい時間♪」のイベントの選択肢下の情報が抜けているため情報を提示します。
![screenshot_2024-01-04_05-57-50](https://github.com/Cilda/UmaUmaChecker/assets/48989004/b67d7609-83a5-448b-830b-cece67ce1c77)

**Comment by Cilda** [comment]
ありがとうございます。
修正しました。
次の更新で変更が適用されます。
