### ISSUE TITLE
SRメジロドーベルのイベント不備

### ISSUE THREAD

**Issue by ameteras2240** [Cilda/UmaUmaChecker#119]
SR根性メジロドーベルの連続イベント1回目「頼れる先輩」が刻み続ける者たちの同名イベント「頼れる先輩」として認識されています。
![screenshot_2024-01-04_06-55-24](https://github.com/Cilda/UmaUmaChecker/assets/48989004/82786b04-d63c-4100-ba96-b3196d9ae95f)
![image](https://github.com/Cilda/UmaUmaChecker/assets/48989004/d929cc32-5d59-422a-b01d-01a2e61bf48e)

**Comment by Cilda** [comment]
ありがとうございます。
同名のイベントが出てくることを考慮していないので現在はイベントデータの修正だけでは対応出来ません。
なので次のバージョンで同じ選択肢が複数ある場合は選択肢の結果を優先するように修正します。

**Comment by Cilda** [comment]
v1.6.3で選択肢から読み取るように修正を加えました。
これで同名のイベントが読み取れるはずです。
