### ISSUE TITLE
イベント「頼れる先輩」の選択肢がちょっと違う

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#124]
![screenshot_2024-01-30_19-36-29](https://github.com/Cilda/UmaUmaChecker/assets/12384865/0218bf80-de44-4b1b-9f30-7f5a0d1d4026)
![Clipboard01fdsfsd](https://github.com/Cilda/UmaUmaChecker/assets/12384865/044a4079-5f14-4e9b-b879-66d6b42e0338)

**Comment by Cilda** [comment]
#119 と同じ問題のようです。
この問題のみなら修正済みですが #120 の問題は解消しないため解決策を模索中です。
