### ISSUE TITLE
新シナリオのイベント「張り切る理由は」はまた追加しなかった。

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#127]
![screenshot_2024-02-26_18-34-36](https://github.com/Cilda/UmaUmaChecker/assets/12384865/3ecd4dfc-4cc5-44bf-95d9-89ec6e8663c9)

張り切る理由は.
https://kamigame.jp/umamusume/page/303700448433467722.html

GAMEWITHはまたUAFのイベントが追加しなかったが、手動で追加するか？
また、たくさんスキルが追加しましたので、スキルの説明を追加してお願いします。

前[[Request] お出かけ可能なキャラのイベント](https://github.com/Cilda/UmaUmaChecker/issues/45)を一覧表示を希望ですが、
今友人など使用率が大幅アップになったので、先に機能追加してもできますか？

よろしくお願いします。

**Comment by Cilda** [comment]
ありがとうございます。
シナリオイベントについては追加します。
おでかけイベントの一覧については、検出するとなると今のUIでは表示が厳しいため別の方法になると思います。

**Comment by Cilda** [comment]
張り切る理由は……を追加しました。

**Comment by Yucie** [comment]
> 張り切る理由は……を追加しました。

２時間前育成の時は反応しなかったけど、いつから追加したの？
認識できないが、更新しなかったが、知らなかった。
