### ISSUE TITLE
新シナリオのイベント「さすらいの道場破ラー,いっしょに遊ぼ」はまた追加しなかった。

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#129]
![screenshot_2024-03-08_20-53-44](https://github.com/Cilda/UmaUmaChecker/assets/12384865/0235c171-7efc-4b95-9044-c03deddb18b7)

https://kamigame.jp/umamusume/page/303700448433467722.html

**Comment by Cilda** [comment]
ありがとうございます。
追加しました。

**Comment by Yucie** [comment]
> ありがとうございます。
> 追加しました。

すいません。[いっしょに遊ぼ]のイベントはまた追加してなかった。

**Comment by Cilda** [comment]
追加しました
