### ISSUE TITLE
[BUG] 夏合宿（3年目）終了(選択肢なしに認識された)

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#132]
![Clipboard01asfddsa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/5aa51f6d-8acf-4363-9ac0-2e4413f8f5bf)
![screenshot_2024-04-20_17-23-15](https://github.com/Cilda/UmaUmaChecker/assets/12384865/e9cfa4f1-2d7c-460f-b7b9-86a2ebe19cba)

**Comment by Cilda** [comment]
ありがとうございます。
明日、選択肢の修正をします。

**Comment by Cilda** [comment]
本日の22時に選択肢なしのイベントが除外されるようになります。
