### ISSUE TITLE
[BUG] イベント「コン・フオーコなアモーレを君に」が選択肢なしになった

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#133]
![Clipboard01ffff](https://github.com/Cilda/UmaUmaChecker/assets/12384865/4f3f9a9f-2c6c-4cb3-a8c7-8f9367af2acc)

**Comment by Cilda** [comment]
こちらで確認した限りだと表示されました。
もう一度確認してもらえますでしょうか。

**Comment by Yucie** [comment]
EVENT.JSON の中に、選択肢１つしか書きませんでした。

                    {
                        "コン・フオーコなアモーレを君に": [
                            {
                                "Title": "ど、どうも……君はエネルギッシュだな",
                                "Effect": "スタミナ+10\n根性+5\nサウンズオブアースの絆ゲージ+5"
                            }
                        ]
                    }
                ]
            },

**Comment by Cilda** [comment]
イベント名が間違っているようなのでスクレイピングを修正します。

**Comment by Yucie** [comment]
今回、初めて選択肢二つ認識され、0.5秒の後は

https://private-user-images.githubusercontent.com/12384865/327633494-4f3f9a9f-2c6c-4cb3-a8c7-8f9367af2acc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODE2MzgsIm5iZiI6MTcxNTA4MTMzOCwicGF0aCI6Ii8xMjM4NDg2NS8zMjc2MzM0OTQtNGYzZjlhOWYtMmM2Yy00Y2IzLWE4YzctOGY5MzY3YWYyYWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmM5MTUzYTdmYzRhMDJiOTg1ZTA4OWRjNGFiMTU1N2E0M2Q2YjJmYjY2M2ZhYmJhNjJjYWI2YzJiN2UyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uK0ukwvNJu2yKxkHRbp_GEimSe3GmioPYqPseH6NTCI


選択肢一つになった。OUTPUT.LOGは下記となります。

[2024-05-07 19:27:22.074843][DEBUG]: [サポートカード] イベント名: コン・フォーコなアモーレを君に
[2024-05-07 19:27:23.062836][DEBUG]: [サポートカード] イベント名: コン・フオーコなアモーレを君に
[2024-05-07 19:27:34.146788][DEBUG]: [サポートカード] イベント名: コン・フォーコなアモーレを君に
[2024-05-07 19:27:35.153402][DEBUG]: [サポートカード] イベント名: コン・フオーコなアモーレを君に

**Comment by Cilda** [comment]
修正をコミットしました。
