### ISSUE TITLE
育成ウマ娘のリスト順について

### ISSUE THREAD

**Issue by PhilipMarshall2024** [Cilda/UmaUmaChecker#139]
こんにちは。　UmaUmaCheckerには非常にお世話になっています。
便利なものを提供していただき、本当にありがとうございます。

要望があるのですが、育成ウマ娘のリストの並び順について
これを★3・★2・★1　等で並べるのではなく、単純にウマ娘名で並び替えていただけないでしょうか。
[ ]で囲まれてる二つ名の部分も無視して、ウマ娘名そのものを基準に五十音順で並び替えてほしいのです。

因子周回でグラスワンダーやエルコンドルパサーを育成する機会が多いのですが、
現行版では一番下の方までスクロールしないと出てこないので、少々使いづらさがあります。

不躾な要望で申し訳ないですが、ぜひご検討をよろしくお願いします。

**Comment by Cilda** [comment]
返信が遅れてすみません。
特に問題がないので、現在の並びからレアリティ関係なくキャラクターの名前の昇順へ変更します。

**Comment by PhilipMarshall2024** [comment]
ご返信ありがとうございます。
また、ご快諾いただき大変有り難うございます。
次回アップデートを心待ちにしております。
