### ISSUE TITLE
4K モニター使ったら、窓が小さすぎ

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#20]
**バグの説明**
４Kモニターの場合は、窓が小さすぎで見にくいです。

![small](https://user-images.githubusercontent.com/12384865/196015760-b3393ca4-ff7d-46b5-b855-49adea24f3b7.png)

UMACRUISEと一緒に起動したら、サーズは半分しかなかった。

ところで、窓のサイズが変えれないので、設定ボタンが押せなかった。

**Comment by nagi-VF** [comment]
DPIによってウィンドウサイズを変更する処理を実装しました。

**Comment by Yucie** [comment]
修正ありがとうございます。
もう少しフォントのサーズを変更できますか？
今フォントのサーズなら、小さくて読みにくいです。
![temp_ff](https://user-images.githubusercontent.com/12384865/196042323-7998926d-836a-4a9d-bf0e-325c4be63890.png)

**Comment by nagi-VF** [comment]
フォントをYu Gothic UIに変更しました。
フォントはcruiseと同じものを使用しています。

**Comment by Yucie** [comment]
修正ありがとうございます。
実は文字が小さくて読みにくかった。
よければ、フォントのサイズが自分設定できるようにできますか？
ご迷惑をかけてすみません。

![temp_ffg2](https://user-images.githubusercontent.com/12384865/196169979-92b0ed79-6d03-4eca-95ef-da15ff37ae89.png)

**Comment by nagi-VF** [comment]
設定からフォントサイズを変更できるように修正しておきます。

**Comment by nagi-VF** [comment]
設定からフォントとフォントサイズを変更できるように修正しました。

**Comment by Yucie** [comment]
今フォントサイズが問題なく読めやすかった。
ありがとうございます。
![temp_ag](https://user-images.githubusercontent.com/12384865/196485805-d7a20d6d-ba03-4955-aa7d-c47e74f47b6d.png)
