### ISSUE TITLE
[外部要望]キャラ認識システム

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#22]
<img width="540" alt="screenshot_1666162227865675" src="https://user-images.githubusercontent.com/12384865/196617770-6f7f363f-f8be-45f4-837a-221dea323ec8.png">
ステータスの画面の時、cruiseは画面認識させ、キャラが自動的に選んだけど、
チェッカーにも追加できますか？

ところで、選択なしのイベントで表示オン／オフ機能も追加できますか？
選択なしのイベントを表示してもあまり意味がないと思いました。

![2022y01m11d_1654219821](https://user-images.githubusercontent.com/12384865/196620508-76625286-db31-4475-89de-b7593b4bceaf.jpg)
友人サポカードのお出かけですが、イベント進行度によって、
お出かけの効果が表示できますか？

要望多すぎで、すみません。

**Comment by nagi-VF** [comment]
検討します。
また要望が3つある形ですのでチケットを分けさせていただきます。

**Comment by nagi-VF** [comment]
タイトルを変更しました。

**Comment by Cilda** [comment]
> ステータスの画面の時、cruiseは画面認識させ、キャラが自動的に選んだけど、 チェッカーにも追加できますか？
ところで、選択なしのイベントで表示オン／オフ機能も追加できますか？
選択なしのイベントを表示してもあまり意味がないと思いました。

こちらについては、別issueを起こしてもらえますか。
複数の内容を1つのissueで管理をできないのでお願いします。
こちらは、キャラ自動認識を実装したのでcloseします。
