### ISSUE TITLE
[外部要望]動画キャプチャや育成途中のステータス

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#24]
追加要望があります。ごめんなさい。
１．FFMPEG を使って、ゲームのシアターとか、動画キャプチャの機能を追加したいです。
２．育成途中にスピード、スタミナなどのデータを記録し、選択の時がデータを見ながら、選択肢を選びたいです。（結構CPU消費しそうなんで、できるかどうかわかりません。なお、Tesseract OCRの数字認識度が低くて違う数値が認識したことがよくあった。。。）

**Comment by nagi-VF** [comment]
要望ありがとうございます。
現状、以前のご要望の変更を行っている最中ですのでこのチケットはそちらの対応が終わり次第ということを
ご承知おきください。

**Comment by Yucie** [comment]
ごめんなさい。また要望があります。。。
ただ３０分で、メモリー使用量が５０Mから５００Mに達した。
メモリーリリースできるかどうかわからないけど、ちょっとメモリー使用量が減らしたいです。
よろしくお願いします。
![error_5](https://user-images.githubusercontent.com/12384865/197138903-200ab076-c8ee-4b94-a6f3-f9c4fc02e4d7.jpg)

**Comment by Yucie** [comment]
４Kのモニターのせいで、メモリー使用量が５０Mから６００M以上に行けた。
また３年目の合宿なのに、４０分ぐらいでこんなにメモリーが使いました。
４Kサイズのせいが？わからないけど、少しメモリーを減らせますか？
ちなみにCRUSIERのほうがいつも３００Mぐらい維持できる
![error10](https://user-images.githubusercontent.com/12384865/197587190-6a5eeba0-f227-41ee-87e9-0b4748d04aed.jpg)

**Comment by Cilda** [comment]
確認します。
なお、こちらではメモリが大量に増える現象を再現できないので少し時間がかかるかもしれません。
早めに対応しますのでしばらくお待ち下さい。

**Comment by Yucie** [comment]
今日あまり時間がないので、育成１回しましたが、イベントがチェックしなくて、はやめに育成しました。
umamusme本体とchecker、両方とも育成中が窓動かないまま、メモリーの使用量があまり増やせなかった。
昨日の育成検証はよくプリントスクリーン押しやウマ本体とcheckerの窓を移動しました。
あれがメモリーリークの原因だと思われた。あるいはゴルシ育成の選択と関係かもしれません。
あまり時間がないので、２次検証やりませんでした。すみません。

**Comment by Cilda** [comment]
また現象が起こった際に、行った操作を詳しく書いてもらえると今後の調査の参考になります。
できればお願いします。

**Comment by Yucie** [comment]
新しいバグが発見しました。

--------バグを再現する手順:-------
umamusume本体の窓サーズが変わったら、
次の選択を認識したとき、メモリーリークが発生しました。

育成→本体のサーズが変わる→（CHECKのメモリー使用量が増やせない）→
ゲーム続き→次のイベント発生→CHECKがイベント認識できる、メモリーリリーズできない→
育成→次のイベント→（本体のサーズ変わらない）→イベント認識できる→メモリーリリーズできない
（さらに、メモリー増えました）

**Comment by Yucie** [comment]
ほかのバグ、（オクリ育成）、窓移動しない、サーズかわない
--------バグを再現する手順:-------
（メモリー使用量６０M）
レッスン→１２月後半→有馬記念にむけて→GI有馬出走→３RDライブ

（使用量６８M）
（この間、メモリー６M増えたけど、そのあとメモリーリリーズしない）

（使用量７４M）
初詣→レッスン→福引
（メモリー増大、リリースしない）

**Comment by Cilda** [comment]
起動時に1回でもプレビューウィンドウを開いた場合にメモリが開放されていませんでした。
v1.3.2をリリースしたので確認してみてください。

**Comment by Yucie** [comment]
タスクマネージャーよりCHECKのほうがメモリーの状態表示できますか？
デッバグモード追加でもかもいませんけど、CHECKも画像のようにメモリーとCPU状態表示できます？
（CPU結構使った場合は１分ごとにメモリー状態を更新かまいませんが）

![error32](https://user-images.githubusercontent.com/12384865/198861928-491c6d51-82ea-4f73-869c-e0c44507ff1b.jpg)

**Comment by Cilda** [comment]
> タスクマネージャーよりCHECKのほうがメモリーの状態表示できますか？ デッバグモード追加でもかもいませんけど、CHECKも画像のようにメモリーとCPU状態表示できます？ （CPU結構使った場合は１分ごとにメモリー状態を更新かまいませんが）
> 
> ![error32](https://user-images.githubusercontent.com/12384865/198861928-491c6d51-82ea-4f73-869c-e0c44507ff1b.jpg)

CPUとメモリ使用率は全体の使用率ですか？
それとも、ツールの使用率だけでよいですか？

**Comment by Yucie** [comment]
CHECKだけの使用量でいいと思います。

**Comment by Cilda** [comment]
- [ ] 動画キャプチャ機能
- [ ] メモリリーク
- [ ] ステータスバー表示機能

**Comment by Cilda** [comment]
v1.3.3でステータスバーを追加しました。

**Comment by Cilda** [comment]
> １．FFMPEG を使って、ゲームのシアターとか、動画キャプチャの機能を追加したいです。
ゲームのキャプチャに関して、専用のキャプチャツールより機能が限定的になりやすい、画質等が劣ると思われるため実装が難しいです。
OBS等のキャプチャツールを利用してキャプチャを行った方が負荷も軽くなると思います。
