### ISSUE TITLE
[Bug]育成ウマ娘の自動認識のメモリー使用量が急激増大

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#26]
**バグの説明**

**再現手順**
バグを再現する手順:
1. ステータス画面（７０Mぐらい）
2. スタート
3. キャラ認識
4. メモリー（９０～１００M以上に達した）
5. 育成じゃなくても（CPU１～５％使用した）

P.S　1.31以前は認識してもあまりメモリー使いませんでした。
![error15](https://user-images.githubusercontent.com/12384865/198678983-d71cde17-2729-4cdb-b1ef-e224c43d8251.jpg)
![error17](https://user-images.githubusercontent.com/12384865/198679096-8f7ac908-6339-4087-8a7e-7e68416e2ab8.jpg)

手動の場合は
![error19](https://user-images.githubusercontent.com/12384865/198684181-47a1aa82-ce15-40db-a93c-821e657c87fe.jpg)
７９M→８４M

手動／自動でもメモリーリークでメモリーとCPUの使用量が大きすぎ、さらにメモリーリリースしません。

![error20](https://user-images.githubusercontent.com/12384865/198680894-54d2280c-80a1-46c6-9a81-23cdab8c8a48.jpg)

P.S　このテストは（umamusume本体やCHECKERも移動しませんでした。本体もサイズ変更しなかった。

そのまま育成したら、イベント１つずつメモリー１０Mぐらい増大。今夜は1.31に戻って育成します。
ごめんなさい
![error21](https://user-images.githubusercontent.com/12384865/198682612-2aeb3c5f-b050-4890-a3d5-5470f86fbadb.jpg)

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
1.31自動認識の場合はメモリー６８M使いました。

![error22](https://user-images.githubusercontent.com/12384865/198683409-2ed3e8a5-af3c-4b2b-a598-7dc1f20fe49f.jpg)

**Comment by Cilda** [comment]
> そのまま育成したら、イベント１つずつメモリー１０Mぐらい増大。
これはイベントを認識する毎に10MBずつメモリ消費が増えるということでしょうか。
(例えば、イベントA認識：90MB→イベントB認識：100MB→イベントC認識：110MB というような)

また起動時のメモリ使用量ですが、tessdata内のtraineddataファイルを差し替えたためその分使用量が増えています。
これは、過去バージョンのjpn1.traineddataに戻すとv1.3.1以前と同じメモリ使用量になると思います。

現状、こちらではメモリリークを修正後からメモリ使用量が増加し続ける問題を確認できないため、よろしければ以下のURLのArtifactsの添付ファイルから確認して見ください。
(同時にCPU使用率が増加するような不要な処理を修正しています。)
https://github.com/Cilda/UmaUmaChecker/actions/runs/3350810860

**Comment by Cilda** [comment]
**補足**
メモリ使用量について、イベントを認識するために内部で画像のイベント名部分を画像処理しています。
そのため、ウマ娘のウィンドウサイズに比例して使用メモリの上がり幅が大きくなります。
なので #22 で不具合を報告していただいた「30分育成すると800MBメモリを消費した」のような不具合でなく、100MBまで上昇してから一切上がらない場合は問題ないと思われます。

**Comment by Yucie** [comment]
動画キャプチャーしました。今１．３２の環境には
https://drive.google.com/file/d/1WIpMmgsNy1BtDlwJC98KpSAb8ivYPrw6/view?usp=sharing

スタート前３２m
checkスタート６８m
イベント７４mぐらい
次のイベント７８mぐらい

イベント１つ４mぐらい増えましたが、１年目１３０mぐらい達しました。

**Comment by Cilda** [comment]
ありがとうございます。
動画を確認したところメモリリークが発生しているような現象は見られませんでした。

念のため、以下のURLにtessdata内のtraineddataファイルを過去の2.5MBのファイルに戻しております。
(3.0MBは認識率が悪かったため)

https://github.com/Cilda/UmaUmaChecker/actions/runs/3350993201
こちらでも確認してみてください。

メモリ使用量が上限なく増加していく問題がなければメモリリークの不具合は修正されたということでいいでしょうか。

**Comment by Yucie** [comment]
了解いたします。
新しいtraindataを使って、メモリー２００m以上達した場合は報告してもいい？

**Comment by Cilda** [comment]
ぜひ報告してください。
不具合に限らず何かあった場合は報告して頂けると嬉しいです。
