### ISSUE TITLE
[外部要望]文字改行

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#27]
説明欄のとこ、文字数によって自動改行できますか？

今のは、３つだけ表示しますが、勿体無いと思っています。
例えば

体力+10
やる気アップ
賢さ+5
『危険回避』のヒントLv+1
セイウンスカイの絆ゲージ+5

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
体力+10/やる気アップ
賢さ+5/『危険回避』のヒントLv+1
セイウンスカイの絆ゲージ+5

このようにカスタム設定できますか？
よろしくお願いします。

**Comment by Cilda** [comment]
文字数による自動改行は見づらくなるので、テキストボックスの最大行数を設定できる方式でも大丈夫でしょうか。

**Comment by Yucie** [comment]
最大行数６行X5択、チェッカーの高さが大丈夫でしょうか？

**Comment by Cilda** [comment]
高さが増えるのは問題ないと思います。
また、最大行数は設定で変更できるようにするため、個別の高さを設定できるようになります。

**Comment by Cilda** [comment]
すべてを表示するのは不可能なので最低限見れる範囲を設定できるようにします。
はみ出た文字は従来通りポップアップ表示で確認で行けると思っています。

**Comment by Cilda** [comment]
表示行数を可変にしたものを本日コミット予定です。
なるべく要望に近い形で実装は行いますが、実装が難しい場合などは要望通りとはならない可能性があります。
ご了承ください。

**Comment by Cilda** [comment]
v1.3.4で実装しています。
