### ISSUE TITLE
[外部要望]イベントの画像自動的にキャプチャー

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#28]
スキップで育成したので、デッバグモードを追加してほしいです。
デッバグモードで、前のイベントが違ったときは自動的に画像キャプチャーできますか？
例えば 20221103220130.jpg
 
よろしくお願いします。

**Comment by Cilda** [comment]
v.1.3.3で追加しました。
ScreenshotsフォルダのAutoSaveに保存されます。
設定から「識別できなかった場合にキャプチャする」を有効にすると動作します。

**Comment by Yucie** [comment]
デッバグの画像をscreenshot_XXXXXXXXよりdebug_XXXXXXXXにしてもらいませんかか？
育成1回したら、合わせて１Gの画像が大きぎです。
検証終わったら、同じ名前のファイルを一括消したいです。
よろしくお願いします。

**Comment by Cilda** [comment]
ファイル名をdebugに変更しています。
actionsの最新のartifactsでテストできると思います。
キャプチャされない識別されなかったイベントに関しては現在調整中ですのでしばらくお待ちください。
