### ISSUE TITLE
[Bug]未認識　SSR賢ブルボン　ステータス『つまらない？』

### ISSUE THREAD

**Issue by L-SMK** [Cilda/UmaUmaChecker#32]
タイトルのイベントが未認識でした。
ご確認お願いいたします。
![screenshot_1670595357332482](https://user-images.githubusercontent.com/26026130/206722604-eb09251b-dc49-44f2-bbf3-1fb1e218819a.png)

**Comment by Cilda** [comment]
ありがとうございます、確認します！

**Comment by Cilda** [comment]
昨日より、イベント情報のスクレイピングに問題があり、イベント情報が一部消失しておりました。
その中にSSR賢さブルボンのイベントも含まれており、イベントが存在しなかったため認識できなかった可能性が高いと思われます。
消された分のイベントを追加しましたので、一度更新を行っていただきもう一度ご確認ください。

**Comment by L-SMK** [comment]
ほかのイベントも色々と無反応だったので、原因がわかって良かったです。
対応ありがとうございました！！

**Comment by Cilda** [comment]
お手数をおかけしました。
問題が直ったのであればこちらとしても一安心です！
