### ISSUE TITLE
[bug]ナリタブライアン　育成ウマ娘イベント　憧憬　未認識

### ISSUE THREAD

**Issue by L-SMK** [Cilda/UmaUmaChecker#33]
タイトルのイベントが未認識でした。
ご確認お願いいたします。
![screenshot_1670855755462381](https://user-images.githubusercontent.com/26026130/207072333-f628ae80-d7d9-40bf-a6c6-c6fc5c85b3cc.png)

**Comment by Cilda** [comment]
v1.3.6で識別できない問題を修正しました。
