### ISSUE TITLE
育成ウマ娘の自動選択で　［稲荷所縁江戸紫］イナリワン　が正常に認識されない

### ISSUE THREAD

**Issue by 9MTtUmj7** [Cilda/UmaUmaChecker#42]
![screenshot_1677094344006370](https://user-images.githubusercontent.com/71086867/220739403-42ee66d2-97f8-45c6-8e5e-0ffc4a0e59c3.png)
［稲荷所縁江戸紫］イナリワン　を育成中にウマウマチェッカーをスタートした状態で育成ウマ娘詳細を開いても
［夢ノ金原］イナリワン　として認識されてしまう

スクリーンショットを添付しました

**Comment by Cilda** [comment]
確認のためにウマウマチェッカーのスクリーンショットで撮影したイナリワンのウマ娘詳細画面を添付してもらってもいいでしょうか。

**Comment by Cilda** [comment]
スクリーンショットありがとうございます。
確認します

**Comment by Cilda** [comment]
v1.4.2で認識できるように修正しました。
