### ISSUE TITLE
[Request]今を駆ける者たちの祖のスキルの効果を追加したい

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#44]
![GFGFDGFD](https://user-images.githubusercontent.com/12384865/222940506-a037d7c4-7471-49da-869b-51f3d5336c41.png)

太陽の叡智 | レース中盤に競り合うと速度が上がる獲得したスキルの数に応じて効果が高まる

大海の叡智 | レース序盤の始めの方に加速力が上がる獲得したスキルの数に応じて効果が高まる

大地の叡智 | レース終盤の中ほどで速度が上がる獲得したスキルの数に応じて効果が高まる

スキルの効果追加したいです。
よろしくお願いします。

P.S イベント名が間違います。
今を駆ける者たちの姐→今を駆ける者たちの祖

![fdsfdsafdsa](https://user-images.githubusercontent.com/12384865/222940621-b6fd1d77-6de4-4f98-903f-833a727de1a5.jpg)

**Comment by Cilda** [comment]
3つのスキルを追加しました。
更新してみてください。

**Comment by Yucie** [comment]
ありがとうございます。
