### ISSUE TITLE
修正しないかも

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#47]
CASE1:

![223331185-cc2dd365-d764-4039-856f-47cd17a95005](https://user-images.githubusercontent.com/12384865/223686858-b4a92ead-510b-4c7b-98a9-b3052f3d09c5.png)
![223337105-80dc7897-b770-4eec-9714-33b9ae9b60bd](https://user-images.githubusercontent.com/12384865/223686865-bfdf56ac-02cc-4722-9037-b72abb585569.png)

成功”にむけて”に認識された

**Comment by Yucie** [comment]
CASE2:

![215267524-d4389d0e-6cc8-4548-9e47-945eac614472](https://user-images.githubusercontent.com/12384865/223687720-6db0c01c-ee3d-4125-ac27-873af0289158.png)
![screenshot_1678260173808467](https://user-images.githubusercontent.com/12384865/223687627-aa9b8e91-7fee-4777-835c-bc50b5b3bb2b.jpg)
![215267170-c4fbe9fc-193c-4645-9ef0-ba63c8640f52](https://user-images.githubusercontent.com/12384865/223687667-75292b7e-a31f-4f87-9f8b-a395fcd4d56e.png)

全部”1stライブ、スタート！”に認識された

**Comment by Yucie** [comment]
CASE3:

![215265665-a83e4f36-1717-42a9-9131-6b2add000821](https://user-images.githubusercontent.com/12384865/223688413-4509350d-1907-4887-9965-6cbf57cceb44.png)

トレーナー並の知識”に認識された。

**Comment by Cilda** [comment]
新シナリオのイベントについてはデータが現在ないため一番一致率の高いイベント名が表示されているようです。
また、グランドライブの楽曲でライブテクニックのタイトルが誤認識される問題については次のバージョンで修正予定です

**Comment by Yucie** [comment]
> 新シナリオのイベントについてはデータが現在ないため一番一致率の高いイベント名が表示されているようです。 また、グランドライブの楽曲でライブテクニックのタイトルが誤認識される問題については次のバージョンで修正予定です

返事が遅くてすみません。
[update] シナリオデータ読み込み処理修正 #301の後、
CASE2の問題がなくなりました。
CASE3のほうも出ませんでした。

CASE1ですが、もうグラマスの育成がもうやりたくないので、（うまく育成できないが、サポカード揃えないが）
検証しませんでした。

**Comment by Cilda** [comment]
CASE1は次バージョンでシナリオイベントの読み込みを変更予定です。

**Comment by Yucie** [comment]
最新のACTIONを使っても、また直してないケース

https://github.com/Cilda/UmaUmaChecker/issues/25#issuecomment-1464843212

https://github.com/Cilda/UmaUmaChecker/issues/25#issuecomment-1464845190


ちなみに、
https://github.com/Cilda/UmaUmaChecker/issues/25#issuecomment-1459639497
”手紙→？”のイベント（あの”？”の認識率が悪かったかも。認識率５０％ぐらい）

ところで、最近のACTIONの更新がログを見たら、チェッカーのほうが反応して、認識されたイベントを表示します。
前は反応しませんでした。

**Comment by Cilda** [comment]
識別率に関しては現在優先対応していますが、これ以上の仕組みが難しいため難航している状況です。
随時改善中ですのでお待ち下さい。
