### ISSUE TITLE
ScenarioEvents.jsonのグラライのオブジェクトにグラマスのイベントが入っている

### ISSUE THREAD

**Issue by taka0913** [Cilda/UmaUmaChecker#48]
動作に影響は無さそうですが「今を駆ける者たちの姐」は本来グラマスのオブジェクトを新規に作成し、そこに入れるべきだと思ったので報告します。

**Comment by Cilda** [comment]
そちらに関しては、次のバージョンにて対応予定です。
暫定処置としてグランドライブに入れています。
