### ISSUE TITLE
最小化、解像度の変更でアプリのクラッシュ

### ISSUE THREAD

**Issue by Kid9N** [Cilda/UmaUmaChecker#49]
**バグの説明**
ウマ娘アプリを最小化、解像度変更などした際に、ウマウマチェッカーがクラッシュする

**再現手順**
バグを再現する手順:
1.ウマムスメの解像度を変更、最小化、表示位置の変更などを行う
2.アプリのクラッシュを確認

**想定される動作**
-

**スクリーンショット**
-

**追加の内容**
使用rev1.4.0α

**Comment by Kid9N** [comment]
再現性3/5

**Comment by Cilda** [comment]
v1.4.1で修正されています。
