### ISSUE TITLE
［Maverick］ナリタブライアン　の育成ウマ娘イベント　意匠　が認識されない

### ISSUE THREAD

**Issue by 9MTtUmj7** [Cilda/UmaUmaChecker#51]
![screenshot_2023-04-20_19-47-46](https://user-images.githubusercontent.com/71086867/233344169-9abcf91e-0d8e-4f14-8d94-27452f5c16ae.png)

**Comment by Cilda** [comment]
確認します。

**Comment by Cilda** [comment]
v1.4.5で修正しました。
