### ISSUE TITLE
[Bug]SSR [絶対皇帝]シンボリルドルフ　のサポートカードイベント　夢の道標　が誤認識される

### ISSUE THREAD

**Issue by 9MTtUmj7** [Cilda/UmaUmaChecker#52]
イベント　夢の道標　が　空の道標　として誤認識されます
![screenshot_2023-04-21_11-40-03](https://user-images.githubusercontent.com/71086867/233585054-54c8762f-6a8f-44e2-bff8-5e868680eb94.png)
イベント　空の道標　は正常に認識されていました

**Comment by Cilda** [comment]
確認します。

**Comment by Cilda** [comment]
応急措置として、イベント名と選択肢の両方でイベントが取得できる場合は、選択肢からのイベント名が優先されるよう修正を行います。

**Comment by Yucie** [comment]
実は同じバグがまたある
[2121](https://user-images.githubusercontent.com/12384865/224469963-b2d92fa4-e038-40f4-b54b-134821045c87.png)
 
”花を見守る者”に認識された

**Comment by Yucie** [comment]
![eeee112](https://user-images.githubusercontent.com/12384865/219864966-50acbdb8-d0ce-474b-8a9d-f2444bda2e97.jpg)
 
 ![0445](https://user-images.githubusercontent.com/12384865/219864970-49fb00d1-538c-4871-9639-b2226ee495c0.png)
 
 間違って、”交感：走力の限界突破に関する質的研究”に認識された

**Comment by Cilda** [comment]
v1.4.6で選択肢を優先するよう修正しました。

**Comment by Yucie** [comment]
夢の道標、空の道標、交感：走力の限界突破に関する質的研究、夢寐：走力の限界突破に関する質的研究が正しく認識できましたが、自分はクローズできなく、報告しかできませんでした。

**Comment by Cilda** [comment]
チケット起票者によって報告はありませんが、正しく認識できたとのことなのでクローズします。
まだ問題があるようでしたら、またチケットを起票してください。
