### ISSUE TITLE
GAMEWITHが”いたずら大計画、始動なのだ！”のイベントを更新する気がなさそう

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#54]
![Clipboard01](https://user-images.githubusercontent.com/12384865/233767526-646a370d-4b73-4466-9b52-59466e5f00ef.jpg)

GAMEWITH
https://gamewith.jp/uma-musume/article/show/387371

kamigame
https://kamigame.jp/umamusume/page/250375428814939840.html

この計画はやめておこう...
効果／体力+10

手動で更新する？

**Comment by Cilda** [comment]
手動で更新するようにします。

**Comment by Cilda** [comment]
更新しました。
