### ISSUE TITLE
[Bug] 会話の時、関係なしのイベントを間違って認識された

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#56]
![Clipboard01333](https://user-images.githubusercontent.com/12384865/233821330-66ff89cc-64a8-4002-a13d-a7a85a6b55e9.jpg)

**Comment by Cilda** [comment]
ログからでは調査ができないため、イベント名と選択肢があるイベントは選択肢が表示されたスクリーンショットを添付お願いします。

**Comment by Yucie** [comment]
![screenshot_2023-04-23_16-29-17](https://user-images.githubusercontent.com/12384865/233828815-1d459f96-5371-47fa-8d1e-6e70b67a2187.jpg)

こっちの夏合宿も別のイベントに認識された。
今回の育成はスキップを使ったので、チャプチャーできなかった。
次の育成でスキップなしでキャプチャします。

**Comment by Yucie** [comment]
![FqtUb61aYAE88qu3333](https://user-images.githubusercontent.com/12384865/233974330-5df528b5-3860-495b-94f1-edd219e804a0.jpg)
![ffsfsfdasda](https://user-images.githubusercontent.com/12384865/233974349-e26f1536-e8b9-4ae6-ac6e-b79ad6fb1207.png)

間違って、合宿終了と認識された。

**Comment by Yucie** [comment]
![Clipboard02dsfsdfasd](https://user-images.githubusercontent.com/12384865/233975529-0141f639-2ff4-4829-938c-9b1ec3fcddc6.jpg)
![screenshot_2023-04-20_18-49-55](https://user-images.githubusercontent.com/12384865/233975585-7150bc7e-e215-4251-895e-b0264d849ee9.jpg)

合宿3年目終了→認識できる
→ほかのイベントが発生→
ほかのイベントに認識された。

**Comment by Yucie** [comment]
また三女神お出かけのイベントもHP回復の時も、一瞬だけど違うイベントが表示されました。

**Comment by Yucie** [comment]
発生のルールが発見しました。
![FormatFactory スクリーンレコーディング20230425_230216 mp4_snapshot_01 04 9302222](https://user-images.githubusercontent.com/12384865/234331123-61d6e3b9-9a75-4c03-812e-c92ef6666d90.jpg)
![233975529-0141f639-2ff4-4829-938c-9b1ec3fcddc62222](https://user-images.githubusercontent.com/12384865/234331144-ed2105d2-37c6-42bd-b517-b83167d19c20.jpg)

**Comment by Cilda** [comment]
キャラクターイベントの選択肢から取得した際に、育成ウマ娘のキャラクターイベントか判定を行うようにしてみると問題がなくなったので、次バージョンに入る予定です。
識別精度については、さらなる向上が行えるように方式について調査中となります。

**Comment by Yucie** [comment]
> キャラクターイベントの選択肢から取得した際に、育成ウマ娘のキャラクターイベントか判定を行うようにしてみると問題がなくなったので、次バージョンに入る予定です。 識別精度については、さらなる向上が行えるように方式について調査中となります。

キャラクター以外にも、サポートカードも同じ現状が起これました。（例：３女神のサポートカード）
サポートカードの関連にも修正が必要でしょうか？
