### ISSUE TITLE
[Request]ダークモードを設定画面にも適用してほしい

### ISSUE THREAD

**Issue by Kid9N** [Cilda/UmaUmaChecker#59]
**バグの説明**
設定のテーマをダークに設定した時、メイン画面だけでなく設定画面もダークにしてほしいです。

**スクリーンショット**
問題の説明に役立つスクリーンショットがある場合は追加してください。

**追加の内容**
問題に関するその他の内容があればここに記載します。
![チェッカー](https://user-images.githubusercontent.com/129973536/233986344-279be71c-6619-4482-8d68-f4bc72f67d21.jpg)

**Comment by nagi-VF** [comment]
追加実装　「テーマ」での設定値を「OS準拠」、「ライト」、「ダーク」の3つにする
