### ISSUE TITLE
[NewFeatures]累積トレーニング効果の表示

### ISSUE THREAD

**Issue by nagi-VF** [Cilda/UmaUmaChecker#6]
グランドライブにおいて獲得楽曲の各種パラメータを累積表示

**Comment by Cilda** [comment]
あと約2ヶ月で新シナリオが実装されるので今更必要なのかという問題があります。
新シナリオが実装されたら、付けられそうな機能があれば付けるという方向性が良いかも？

**Comment by Cilda** [comment]
新シナリオが発表されたため現状は対応はなしとなります。
