### ISSUE TITLE
[Bug?] ［華麗なる紅玉］ダイイチルビーの無茶は厳禁！イベントがちょっと違う

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#60]
![Clipboard01fsdfsda](https://user-images.githubusercontent.com/12384865/234022629-fdc30ffa-a9f1-4764-a6d7-ce0977b349e6.jpg)

GAMEWITHのほうが正しい→
×使命のためにも、今は休もう→〇勝利を掴むために、今は休もう
https://gamewith.jp/uma-musume/article/show/391235

あと

危険だと判断したら、すぐに止めるよ
失敗の時
やる気3段階ダウン
直前のトレーニングに応じたステータス-10
5種ステータスからランダムに2種を-10
『練習ベタ』になる
---------------
成功の時
体力+10
『練習上手◯』になる

このように分別できますか？
よろしくお願いします。

**Comment by Cilda** [comment]
修正します。

**Comment by Cilda** [comment]
v1.5.0で修正されています。
