### ISSUE TITLE
[Bug] 夢寐：走力の限界突破に関する質的研究の精確度がまた足りない

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#65]
![Clipboard01fdsafdsaf](https://user-images.githubusercontent.com/12384865/235343006-ba8e910d-ac7e-47f8-ba76-45e4a80f9be9.jpg)
![ggdgdsfg](https://user-images.githubusercontent.com/12384865/235343014-18d9e9aa-bbab-48de-aae7-48646b677976.png)

間違って”疾駆：走力の限界突破に関する質的研究”に認識された。

**Comment by Cilda** [comment]
そのイベントについてはイベント名が似ていて選択肢がないため現在の精度では識別が困難です。
精度向上については行っていますが、イベント自体が選択肢なしのイベントのため、すぐ修正は必要ないと考えています。
