### ISSUE TITLE
[Bug?] ［Nevertheless］ナリタタイシンの言わないでイベントがちょっと違う

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#66]
![Clipboard01dsfdsfdsa](https://user-images.githubusercontent.com/12384865/235886739-f5d77e1d-2d40-4d1d-a2b4-03b1b5515b26.jpg)

やる気2段階ダウン
練習ベタになった

**Comment by Cilda** [comment]
修正しました。
次のスクレイピングで更新されます。
