### ISSUE TITLE
[Bug] 別に、邪魔しないでが違うイベントに認識された

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#72]
![Clipboard01sdfasdfas](https://user-images.githubusercontent.com/12384865/236735284-9cd6dcfe-d0fa-43c7-9b6d-58c112b14abb.jpg)
![ggdgdsfgxsA](https://user-images.githubusercontent.com/12384865/236735845-98ca3626-7e37-4dc1-b243-929fc10ea080.png)

サポートRが全部削除されてから、認識できなくなった。

**Comment by Cilda** [comment]
調査したところデータに問題はなく、イベント選択肢を優先しているため同名の選択肢の別イベントが表示されているようでした。
現在、従来通りイベント名を優先的に識別しつつ精度が向上するよう修正しています。

**Comment by Yucie** [comment]
たぶん＃56も同じ原因でバグが起こったけど、修正が終わったら、一緒にクローズできそうだ。

https://github.com/Cilda/UmaUmaChecker/issues/56#issue-1679864285

**Comment by Cilda** [comment]
また問題があるようでしたらissueの起票をお願いします
