### ISSUE TITLE
[Request] 認識されたイベントのログを追加したい

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#73]
1.　スキップを使ったら、一瞬認識されたイベントが記録できなかった。
2. 　サポカードのイベント発生率を計算し、次の育成が簡単計算できるようになってほしい。

**Comment by Cilda** [comment]
ログに認識されたイベント名を書くようにすれば問題ないでしょうか？

**Comment by Yucie** [comment]
イベント名だけいいです。
ありがとうございます。

**Comment by Yucie** [comment]
ちょっと改善したいことがありますが

![Clipboard0133434343](https://github.com/Cilda/UmaUmaChecker/assets/12384865/b62b9e53-a266-42ab-9c3f-d7307b820bf6)

１．認識されたイベントでも、頻繁に認識されたら、0.01秒ごとに書き込まれた。これでログが非常に長くなった。（同じイベントが300以上も書き込まれた）
提案：イベントを認識されたら、 string に記録し、次認識されたイベントは  ＳＴＲＩＮＧと同じだと、スキップ処理になる。
 
２．記録されたイベントは分析用だったら、デバッグのログと一緒に記録したら、ファイルサイズがすごく大きくなった。
提案：デバッグ用と分析用のログは別々のファイルになってほしい。

３．デバッグのファイルはＯＵＴＰＵＴ。ＬＯＧですが、ファイルが一つしかないので、イベントが認識しつづったら、１０Ｍ以上になった。
提案：ＳＣＲＥＥＮＳＨＯＴのような（screenshot_2023-04-10_08-15-11）、デバッグ用、分析用のファイル名と記録の日の形に処理したいです。
