### ISSUE TITLE
[Bug] ”どこまでも”のイベントですが、スズカのサポカードよりチームサポカードのほうが選択された

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#74]
![Clipboard01dsfsd](https://github.com/Cilda/UmaUmaChecker/assets/12384865/6406ecd8-7eea-4f85-a1dd-7c9a250fefa7)
![screenshot_2023-05-17_15-40-06](https://github.com/Cilda/UmaUmaChecker/assets/12384865/d1e7fee5-c4a9-47e8-b14b-ebd1e6d13365)

**Comment by Cilda** [comment]
報告ありがとうございます。
現在、全体的な精度向上のために修正を行っているのでしばらくお待ちください。

**Comment by Yucie** [comment]
精度向上の提案ですが、先に指定のエリアで画像を取って、
そのあと、白のＰＩＸＡＬ（２５５，２５５，２５５）だけ取って、ほかのカラーは全部（０，０，０）にする。
少し処理時間がかかりましたが、（ＰＹＴＨＯＮなら１～２秒ぐらい、Ｃ++ならわかりません）、
その処理した画像をTesseract OCRに認識したら、精度が少し上がれるようです。

**Comment by Cilda** [comment]
ありがとうございます。
画像の二値化は既に行っています。
