### ISSUE TITLE
[Bug] 花を見守る者に間違って認識された

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#77]
![fsfdsafadsf](https://github.com/Cilda/UmaUmaChecker/assets/12384865/e1c40173-a7db-4852-b46c-2ef7d92442b8)

![Clipboard01safdsfdsa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/e0268e77-519c-4c73-968a-918927944ff2)

**Comment by Cilda** [comment]
シナリオイベント「ウマ娘を見守るもの」がデータ上にはないため、一番類似しているイベントが表示されていると思います。

**Comment by Cilda** [comment]
該当のイベントは効果がないようなのでイベントの追加は考えていません。
効果があるイベントが存在するようでしたらまた報告してください。
ありがとうございます。
