### ISSUE TITLE
[Question] 選択なし、効果があるイベントですが

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#79]
![224469863-15ac1ff6-3b07-4804-adbe-04351aadf1b2](https://github.com/Cilda/UmaUmaChecker/assets/12384865/002890d1-cc72-4f5b-91cc-850f50f75ba7)

![Clipboard01fsdafdsfdsadsfa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/7049469d-424b-4b3b-85bf-930d2e259db4)

[DEBUG]: イベント不一致 識別文字[和金骨石を屋き満して, 金則石を情き満じで, 生同石を屋き江して, 金則石を屋き済して]

この金剛石を履き潰しては認識できないけど、

                        "金剛石を履き潰して": [
                            {
                                "Title": "選択肢なし",
                                "Effect": "賢さ+10\nスピード+7\nスタミナ+7\n『優位形成』のヒントLv+1\nメジロラモーヌの絆ゲージ+5"
                            }
                        ]
                    },

 ＥＶＥＮＴ．ＪＳＯＮの中に載ってます。

このようなイベントは、今後は報告するかしないかわかりませんが、報告必要がどうか教えてください。

**Comment by Cilda** [comment]
選択肢がないイベントについては報告はなくて問題ありません。
将来的な識別率の向上で修正予定とさせてください。

**Comment by Yucie** [comment]
報告なし→知らない→識別修正がわからない→このまま修正なし
認識できない→分析ログも書き込まなかった

このようになるかもしれませんが。。。この認識でいいですか？

**Comment by Cilda** [comment]
問題ないです。
選択肢が存在するイベントに関しては、今まで通りご報告いただけたらと思います。
