### ISSUE TITLE
[Bug] "一瞥にて"が認識できなかった

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#81]
![Clipboard01dfsdsaf](https://github.com/Cilda/UmaUmaChecker/assets/12384865/31f95667-9ddb-411e-bde9-ba4bb849aaec)
![screenshot_2023-05-29_12-19-37](https://github.com/Cilda/UmaUmaChecker/assets/12384865/19f174f7-2ca5-441a-a8b2-666a994b14d4)

P.S 昨日認識できたけど、今日アップデートの後、認識できなくなった。
アップデートの影響かもしれません。

**Comment by Yucie** [comment]
![screenshot_2023-05-31_18-52-39](https://github.com/Cilda/UmaUmaChecker/assets/12384865/0ebd6e90-7f1a-4c05-abe2-311950462b12)

[2023-05-31 18:52:01.607118][DEBUG]: イベント不一致 識別文字[一首にて, 一首にて, 一普にて, 一紹にて]

このサイズにも認識できなかった。

**Comment by Cilda** [comment]
調査します。

**Comment by Cilda** [comment]
v1.5.1で選択肢の読み取り処理を改善しました。

**Comment by Yucie** [comment]
ありがとうございます。
ＴＰ使い切れたので、明日試します。
