### ISSUE TITLE
[Bug?] ”溢れる情熱”のスキル効果

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#85]
![Clipboard01fdsafdsfa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/4ba10c03-d922-420b-b7e3-ea6280d70845)

スキルの効果がまた追加してないです。
ＳＫＩＬＬ。ＪＳＯＮも載ってなかった。

**Comment by Yucie** [comment]
調べたら、またこのスキルはまたスキル効果が載ってなかった。
'昂る鼓動'
'盤石の構え'

**Comment by Cilda** [comment]
報告ありがとうございます。
追加します。

**Comment by Cilda** [comment]
スキルを追加しました。
