### ISSUE TITLE
6月19日追加されたサポカードがチェッカーに追加しなかった。

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#88]
マヤノトップガン(SSR)
https://gamewith.jp/uma-musume/article/show/404589
コパノリッキー(SR)
https://gamewith.jp/uma-musume/article/show/404588

Event.JSONも載らなかった。
なお、新しいスキルも追加したので、スキル説明を追加してお願いします。

**Comment by Cilda** [comment]
追加します

**Comment by Cilda** [comment]
何らかの問題が原因でスクレイピングが動いていなかったようです。
手動でイベント、キャラ、スキルのデータを更新しています。
