### ISSUE TITLE
[Request] V1.60の幅など変更したい 

### ISSUE THREAD

**Issue by Yucie** [Cilda/UmaUmaChecker#91]
![Clipboard01ffsdfdsa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/ec89c57b-bfbd-4a3c-bf29-eb8c0a0877ee)

スクリーンショットと画像を取るボタンが小さすぎで間違ったボタンを押しやすくて、もっと大きくなってほしいです。
赤い〇の画像を撮影機能がわからない、使用方法が書いてほしいです。
チェッカーの幅は前より小さくて、100PXほど大きくなりたいです。

**Comment by Cilda** [comment]
高DPI環境ではボタンサイズが小さすぎるため、2つのボタンについては最適な形式を模索します。
ありがとうございます！

**Comment by Cilda** [comment]
README.mdに説明を追記しています。

**Comment by Yucie** [comment]
あと、CPUとMEMの使用率の機能が使えなくなった

**Comment by Cilda** [comment]
ステータスバーについては修正します。

**Comment by Yucie** [comment]
1.6.0
![Clipboard01fsdfdsafs](https://github.com/Cilda/UmaUmaChecker/assets/12384865/3dc6dc49-434d-421d-92b1-b39f54f8acb8)

1.51
![246719533-28b643b2-eaf0-4202-8d7f-7f2bb27d7ca7fsafdsafdsa](https://github.com/Cilda/UmaUmaChecker/assets/12384865/771e2407-f31a-411e-9113-99ec97837654)

バージョン1.6.0の幅はバージョン1.5.1より771PXから626PXまで縮んだので、せめて100PXが追加したいです。
１．育成ウマ娘の幅が足りなくて、名前がすべて表示できなくなった。

２．選択肢の表示欄もかなり縮んだので、前より７割しか表示になった。せめて100PXが追加したいです。
